version: '3'

services:
  app:
    image: juni:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on: 
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db

  db:
    image: library/postgres:11.1-alpine
    shm_size: 4g
    restart: unless-stopped
    volumes: 
      - ./db.sql:/tmp/db.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
      - POSTGRES_DB=juni
